# æœºåœºè®¢é˜…ï¼Œåç§°ä¸èƒ½é‡å¤
proxy-providers:
  Airport_02:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy:  DIRECT
    url: "è®¢é˜…"
    override:
      skip-cert-verify: true
      udp: true
      down: "50 Mbps"
      up: "10 Mbps"
      
# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
global-ua: clash.meta
    
# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
# interface-name: eth0  ï¼ˆè·¯ç”±å™¨ä¸‹æ ¹æ®æƒ…å†µæŒ‡å®šå‡ºç«™æ¥å£ï¼‰
authentication:
  - name:passwd
  
geodata-mode: false
# GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼ˆstandardï¼šæ ‡å‡†åŠ è½½å™¨/memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)ï¼‰
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
# ä¸‹è½½é¢æ¿åœ°å€å¯æ›´æ¢ï¼šhttps://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip

# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true
  
# æµé‡å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    
# ä»£ç†æ¨¡å¼
tun:
  enable: true
  stack: mixed
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  # æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
  # é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:                          # Fake-ip è¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®IP
    - "+.lan"
    - "+.local"
    - geosite:private
    - geosite:cn
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:private_domain,cn_domain":
    - 223.5.5.5
    - 119.29.29.29
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
 
   
 
# ç­–ç•¥ç»„
proxy-groups:
#åˆ†æµåˆ†ç»„
  - {name: èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [ é¦™æ¸¯æ•…è½¬, æ¸¯ç¾æ•…è½¬, å…¨èŠ‚æ•…è½¬, å…¨éƒ¨èŠ‚ç‚¹], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png }
  - {name: YouTube, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/YouTube.png }
  - {name: Google, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png }
  - {name: ChatGPT, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png }
  - {name: GitHub, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©,DIRECT], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/github.png }
  - {name: Microsoft, type: select, proxies: [DIRECT, èŠ‚ç‚¹é€‰æ‹© ], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Microsoft.png }  
  - {name: Spotify, type: select, proxies: [DIRECT, èŠ‚ç‚¹é€‰æ‹© ], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Spotify.png }
  - {name: Cloudflare, type: select, proxies: [DIRECT, èŠ‚ç‚¹é€‰æ‹© ], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Flyint.png }
  - {name: Telegram, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png }
  - {name: NETFLIX, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Netflix.png }
  - {name:ğŸ Apple, type: select, proxies: [DIRECT, èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Apple.png }
  - {name: å…¨çƒç›´è¿, type: select, proxies: [DIRECT, èŠ‚ç‚¹é€‰æ‹©], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/ASN.png }
  - {name: æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ èŠ‚ç‚¹é€‰æ‹©,DIRECT], icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png }

#èŠ‚ç‚¹åˆ†ç»„
  - {name: é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(æ¸¯|HK|HK2|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Auto.png }
  - {name: æ¸¯ç¾æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "(?=.*(æ¸¯|HK|HK2|US|(?i)Hong))^((?!(SG|å°|éŸ©|æ–°|NG)).)*$",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png  }
  - {name: å…¨èŠ‚æ•…è½¬, type: fallback, include-all: true, interval: 300, filter: "^((?!(DIRECT)).)*$", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Bywave.png }
  - {name: è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(DIRECT)).)*$",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png }
  - {name: é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/SWCloud.png }
  - {name: é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png }
  - {name: æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ—¥|jp|japan",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png }
  - {name: ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png }
  - {name: å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true, filter: "^((?!(DIRECT)).)*$",  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Suda.png }

# åˆ†æµPolicy 
rules:
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,direct1, å…¨çƒç›´è¿
  - RULE-SET,proxy1, èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,proxylite, èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ai, ChatGPT
  - RULE-SET,ai-classical, ChatGPT
  - RULE-SET,github_domain, GitHub
  - RULE-SET,youtube_domain, YouTube
  - RULE-SET,twitter_domain, èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,spotify_domain, Spotify
  - RULE-SET,bilibili_domain, å…¨çƒç›´è¿
  - RULE-SET,google_domain, Google
  - RULE-SET,microsoft_domain, Microsoft
  - RULE-SET,telegram_domain, Telegram
  - RULE-SET,netflix_domain, NETFLIX
  - RULE-SET,cloudflare_domain, Cloudflare
  - RULE-SET,geolocation-!cn, èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,gfw_domain, èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,cn_domain, å…¨çƒç›´è¿
  - RULE-SET,google_ip, Google,no-resolve
  - RULE-SET,netflix_ip, NETFLIX,no-resolve
  - RULE-SET,telegram_ip, Telegram,no-resolve
  - RULE-SET,cn_ip, å…¨çƒç›´è¿
  - MATCH, æ¼ç½‘ä¹‹é±¼

# åˆ†æµé”šç‚¹ 
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  domainplus: &domainplus {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 1800, behavior: classical, format: text}

# è¿œç¨‹è§„åˆ™ 
rule-providers: 
  #è‡ªç”¨è§„åˆ™
  direct1: { <<: *class, url: "https://raw.githubusercontent.com/Nana2222/Rules/refs/heads/main/Direct.list" }
  proxy1: { <<: *class, url: "https://raw.githubusercontent.com/Nana2222/Rules/refs/heads/main/ProxyLite.list" }
  
  #qcyè‡ªå®šä¹‰æµ‹è¯•è§„åˆ™
  proxylite: { <<: *domainplus, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/master/ProxyLite.list" }
  ai: { <<: *domainplus, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/master/AI.list" }
  
  #æ­£å¼è§„åˆ™
  
  # éšç§ç½‘ç»œ/å±€åŸŸç½‘
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }

  # äººå·¥æ™ºèƒ½
  ai-classical: {<<: *class,  url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Clash/Rules/AI.list}
  
  # æ²¹ç®¡è§†é¢‘
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  
  # Cloudflare
  cloudflare_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.mrs" }
  
  # Twitter
  twitter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  
  # Bilibili
  bilibili_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs" } 
  
  # Spotify
  spotify_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs" }  
  
  # è°·æ­ŒæœåŠ¡
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  
  # GitHub
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  
  # ç”µæŠ¥ä¿¡æ¯
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  
  # Netflix
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
  
  # å¾®è½¯æœåŠ¡
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  
  # è‹¹æœæœåŠ¡
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs" }
  
  # GFW
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs" }
  
  # å›½å¤–ç½‘ç«™
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  
  # å›½å†…ç½‘ç«™
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }

